#!/bin/bash
# Capture and split KiloMoana underway feed on stdin

outdir=${1:-.}
[ ! -d "$outdir" ] && mkdir "$outdir"

GPGGAFILE="$outdir/KM_GPGGA_feed.txt"
GPVTGFILE="$outdir/KM_GPVTG_feed.txt"
FLORFILE="$outdir/KM_flor_feed.txt"
METFILE="$outdir/KM_met_feed.txt"
UTHSLFILE="$outdir/KM_uthsl_feed.txt"

awk \
    -v gpgga=$GPGGAFILE \
    -v gpvtg=$GPVTGFILE \
    -v flor=$FLORFILE \
    -v met=$METFILE \
    -v uthsl=$UTHSLFILE \
    '
    /^[^$]/ {date=$1 " " $2 " " $3 " " $4 " " $5 " " $6};
    $7 == "uthsl" {print $0 >> uthsl; fflush(uthsl); next};
    $7 == "flor" {print $0 >> flor; fflush(flor); next};
    $7 == "met" {print $0 >> met; fflush(met); next};
    /^\$GPGGA/ {print date, $0 >> gpgga; fflush(gpgga); next};
    /^\$GPVTG/ {print date, $0 >>gpvtg; fflush(gpvtg); next};
    '
